parameters:
#    mew_pipe_user.example.class: MewPipe\UserBundle\Example

services:
#    mew_pipe_user.example:
#        class: %mew_pipe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    mew_pipe.openid_user_manager:
            class: MewPipe\UserBundle\Entity\OpenIdUserManager
            arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]