mew_pipe_video_homepage:
    path:     /home
    defaults: { _controller: MewPipeVideoBundle:Default:index }

mew_pipe_video_upload:
    path:     /upload
    defaults: { _controller: MewPipeVideoBundle:Default:UploadVideo }
