mew_pipe_video_homepage_pager:
    path:     /page/{page}/{max}/{sort}/{direction}
    defaults: { _controller: MewPipeVideoBundle:Default:index, page:1, max:5, sort:'createdAt', direction:'desc' }
    requirements:
        page: \d+
        max: \d+
        direction: asc|desc

mew_pipe_video_upload:
    path:     /upload
    defaults: { _controller: MewPipeVideoBundle:Default:UploadVideo }
