<?php

namespace Proxies\__CG__\MewPipe\VideoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Comments extends \MewPipe\VideoBundle\Entity\Comments implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'id', 'video', 'user', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'comment1', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'comment2', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'comment3');
        }

        return array('__isInitialized__', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'id', 'video', 'user', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'comment1', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'comment2', '' . "\0" . 'MewPipe\\VideoBundle\\Entity\\Comments' . "\0" . 'comment3');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Comments $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment1($comment1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment1', array($comment1));

        return parent::setComment1($comment1);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment1', array());

        return parent::getComment1();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment2($comment2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment2', array($comment2));

        return parent::setComment2($comment2);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment2', array());

        return parent::getComment2();
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', array());

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', array($video));

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment3', array());

        return parent::getComment3();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment3($comment3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment3', array($comment3));

        return parent::setComment3($comment3);
    }

}
