<?php

namespace MewPipe\VideoBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $sort
     * @param $direction
     *
     * @return array
     */
    public function getListVideo($sort, $direction)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('v')
            ->from($this->_entityName, 'v')
            //->join('o.client', 'cl')
            ->orderBy('v.'.$sort,$direction);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
